services:
  - type: web
    name: sso-dirap-teste
    runtime: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sso-dirap-teste-db
          property: connectionString
      - key: SSO_ADMIN_EMAIL
        sync: false
      - key: SSO_ADMIN_PASSWORD
        sync: false

databases:
  - name: sso-dirap-teste-db
    databaseName: sso_dirap_teste
    plan: free
    ipAllowList: []
