# Ative com --spring.profiles.active=rede somente no micro central.
server.address=0.0.0.0
server.port=${SSO_PORT:8080}
spring.datasource.url=${SSO_DB_URL:jdbc:postgresql://localhost:5432/servicosocial}
spring.datasource.username=${SSO_DB_USER:sso_app}
spring.datasource.password=${SSO_DB_PASSWORD:}
